# Generated by Django 5.2.7 on 2025-10-04 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_user_avatar_remove_user_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='main.movie')),
            ],
        ),
    ]
