# Generated by Django 5.2.7 on 2025-10-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesMovie',
            fields=[
            ],
            options={
                'verbose_name': 'Series',
                'verbose_name_plural': 'Series',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.movie',),
        ),
    ]
