# Generated by Django 5.2.7 on 2025-10-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_seriesmovie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosource',
            name='movie',
        ),
        migrations.DeleteModel(
            name='SeriesMovie',
        ),
        migrations.AddField(
            model_name='episode',
            name='quality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='VideoSource',
        ),
    ]
