# Generated by Django 5.2.7 on 2025-10-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_videosource_movie_delete_seriesmovie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
    ]
