# Generated by Django 5.2.7 on 2025-10-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='is_comment',
            field=models.BooleanField(default=False),
        ),
    ]
