# Generated by Django 5.2.7 on 2025-10-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rating_is_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='upload_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for video upload', max_length=255, null=True),
        ),
    ]
