# Generated by Django 5.2.7 on 2025-10-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_episode_upload_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='upload_task_id',
        ),
    ]
