# Generated by Django 5.2.7 on 2025-10-11 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_episode_upload_task_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Bannerlar'},
        ),
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['season', 'episode_number'], 'verbose_name': 'Epizod', 'verbose_name_plural': 'Epizodlar'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created_at'], 'verbose_name': 'Film', 'verbose_name_plural': 'Filmlar'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='main.movie', verbose_name='Film'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Davomiyligi'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_number',
            field=models.PositiveIntegerField(verbose_name='Epizod raqami'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='main.movie', verbose_name='Film'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='quality',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sifat'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Chiqish sanasi'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.PositiveIntegerField(default=1, verbose_name='Mavsum'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', to='main.genre', verbose_name='Janrlar'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating_avg',
            field=models.FloatField(default=0.0, verbose_name="O'rtacha reyting"),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Reytinglar soni'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Chiqish yili'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('movie', 'Movie'), ('series', 'Series')], default='movie', max_length=10, verbose_name='Turi'),
        ),
    ]
